### ISSUE TITLE
Incorporation of Pictures

### ISSUE THREAD

**Issue by JacobSchmitt** [omnilingo/omnilingo#118] opened 2021-03-14 16:46 UTC
Add an option where an audio file will be played and the user selects pictures of things that are said in the audio stream. This could help users start to actually learn new words from the app

**Comment by d33tah** [comment] 2021-03-14 17:15
Sounds like a duplicate of #42

**Comment by JacobSchmitt** [comment] 2021-03-14 17:16
I think you're right, sorry about that

**Closed** 2021-03-14 17:17 UTC
